mysite/mysite/urls.py
from django.conf.urls import include, url, patterns
from django.contrib import admin

# class AccessUser:
#     has_module_perms = has_perm = __getattr__ = lambda s,*a,**kw: True
#
# admin.site.has_permission = lambda r: setattr(r, 'user', AccessUser()) or True

from polls import  views
urlpatterns = [
    url(r'^core/', include('polls.urls', namespace='polls')),
    url(r'^', include('polls.urls')),
    url(r'^admin/', admin.site.urls),
    # url(r'^$', views.home,),
]

from django.conf import settings
import os
if settings.DEBUG404:
    urlpatterns += \
        patterns(
            '',
            (r'^static/(?P<path>.*)$', 'django.views.static.serve',
             {'document_root': os.path.join(os.path.dirname(__file__),'..', 'static')}),
        )

mysite/polls/urls.py
# from django.conf.urls import url
from django.conf.urls import patterns, include, url
from polls.controller import authController
from . import views

urlpatterns = [
    url(r'^$', views.index, name='polls'),
    url(r'^home/$', views.home, name='home'),
    url(r'^highchart/$', views.highchart, name='highchart'),
    url(r'^highchart/api/$', views.highchart_api, name='highchart_api'),
    url(r'^pages/(?P<page_name>[\w\-]+)/$', views.load_page, name='load_page'),
    url(r'^page/file_upload/$', views.file_upload, name='file_upload'),

    url(r'^demo/(?P<pk>\d+)/(?P<id>\d+)/$', views.demo, name='demo'),

    url(r'^login/$', authController.login, name='login'),
    url(r'^logout/$', authController.logout, name='logout'),
    url(r'^login/pages/$', authController.load_login_page, name='login_page'),
]

mysite/polls/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.
import datetime
from django.db import models
from django.utils import timezone
import logging
logger = logging.getLogger(__name__)


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')


    def __str__(self):  # __unicode__ on Python 2
        return self.question_text


    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'



class Choice(models.Model):
    question = models.ForeignKey(Question)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def _get_data(self,input_data=None, case=None, **kwargs):
        # if kwargs is not None:
        #     for key, value in kwargs.iteritems():
        #         print "%s == %s" % (key, value)
        if input_data:
            data = input_data.filter(**kwargs)
        else:
            data = Choice.objects.filter(**kwargs)
        if case:
            logger.debug("CASE is %s",case)
        return data

    def _update_data(self,input_data=None, **kwargs):
        if input_data:
            data = input_data.update(**kwargs)
        else:
            data = Choice.objects.update(**kwargs)

    def __str__(self):  # __unicode__ on Python 2
        return self.choice_text

mysite/suit/models.py
# Just an empty models.py file, so that we can run tests

mysite/polls/forms.py
__author__ = 'root'

from django import forms
from django.forms import widgets, ModelForm
from .models import *
# from django import forms
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import User
from django.utils import timezone
import datetime

import logging
logger = logging.getLogger(__name__)

class FileIUploadForm(forms.Form):
    file = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True, 'class': 'form-control'}))

mysite/polls/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render

# Create your views here.
import logging
import json
from .models import *
from .forms import *
logger = logging.getLogger(__name__)
from django.http import HttpResponse
from utils.filter import custom_login_required, get_templates_path
from django.shortcuts import render


def load_page(request, page_name):
    page = 'templates/sb-admin/pages/%s.html' % page_name
    page = get_templates_path(page)
    logger.debug(page)
    return render(request, page)

# @custom_login_required
def index(request):
    # logger.debug("=================LOGIN=OK=================")
    # return HttpResponse("Hello, world. You're at the polls index.")
    page = get_templates_path('templates/sb-admin/base.html')
    # logger.debug(page)
    return render(request, page, {})

# @custom_login_required
def home(request):
    data = Choice()._get_data(choice_text__in=['Bad','Good'])
    for i in data:
        logger.debug(i)
    data1 = Choice()._get_data(input_data=data,choice_text__in=['Bad'])
    for i in data1:
        logger.debug("==%s==",i)
    Choice()._update_data(input_data=data1,choice_text='Very Bad')

    return HttpResponse("Hello, world. You're at the polls Home.")

# @custom_login_required
def demo(request,pk,id):
    logger.debug('PK: %s ID: %s',pk,id)
    return HttpResponse("Hello, world. You're at the polls Home. PK:"+str(pk)+" ID:"+str(id))

def highchart_api(request):
    data = [{
        'name': 'Year 1800',
        'data': [107, 31, 635, 203, 2]
    }, {
        'name': 'Year 1900',
        'data': [133, 156, 947, 408, 6]
    }, {
        'name': 'Year 2012',
        'data': [1052, 954, 4250, 740, 38],
        'marker': {'fillColor': '#BF0B23', 'radius': 10},
        'url': "{% url 'polls:home' %}",
    }]
    cata = ['Africa', 'America', 'Asia', 'Europe', 'Oceania']
    response_data = [data,cata]
    return HttpResponse(json.dumps(response_data), content_type="application/json")

def highchart(request):
    # return HttpResponse("Highchart Demo")

    # page = "C:/Python27/Scripts/mysite/templates/polls/highchart.html"
    page = get_templates_path('templates/polls/highchart.html')
    # logger.debug(page)
    return render(request, page, {})


# fp = open(unicode(path2, "utf-8"))

def file_upload(request):

    if request.method == 'POST':
        logger.debug("request.POST: %s",request.POST)
        form = FileIUploadForm(request.POST)
        logger.debug(form)
        file = request.FILES['file']
        logger.debug("file: %s",file)
        path = file.temporary_file_path
        logger.debug("path: %s", path)
        # logger.debug(abc)
    # page = 'sb-admin/pages/mypages/%s.html' % page_name
    page = get_templates_path('templates/sb-admin/pages/file_upload.html')
    logger.debug(page)
    form = FileIUploadForm()

    return render(request, page, {'form': form})

mysite/suit/templates/reversion/change_list.html
{% extends "admin/change_list.html" %}
{% load i18n admin_urls %}

{% block object-tools-items %}
{% if not is_popup %}
<a href="{% url opts|admin_urlname:'recoverlist' %}" class="recoverlink btn">
    <i class="icon-repeat"></i>&nbsp;
    {% blocktrans with cl.opts.verbose_name_plural|escape as name %}Recover deleted {{ name }}{% endblocktrans %}</a>
{% endif %}
{{block.super}}
{% endblock %}

mysite/suit/templates/reversion/object_history.html
{% extends "admin/object_history.html" %}
{% load i18n %}


{% block content %}
<div id="content-main">

    <div class="alert alert-info">{% blocktrans %}Choose a date from the list below to revert to a previous version of this object.{% endblocktrans %}</div>

    <div class="module">
        {% if action_list %}
        <table id="change-history" class="table table-bordered table-condensed table-striped">
            <thead>
            <tr>
                <th scope="col">{% trans 'Date/time' %}</th>
                <th scope="col">{% trans 'User' %}</th>
                <th scope="col">{% trans 'Comment' %}</th>
            </tr>
            </thead>
            <tbody>
            {% for action in action_list %}
            <tr>
                <th scope="row"><a href="{{action.url}}">{{action.revision.date_created}}</a></th>
                <td>
                    {% if action.revision.user %}
                    {{action.revision.user.username}}
                    {% if action.revision.user.first_name %} ({{action.revision.user.first_name}} {{action.revision.user.last_name}}){% endif %}
                    {% endif %}
                </td>
                <td>{{action.revision.comment|linebreaksbr|default:""}}</td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
        {% else %}
        <div class="alert alert-warn">{% trans "This object doesn't have a change history. It probably wasn't added via this admin site." %}</div>
        {% endif %}
    </div>
</div>
{% endblock %}

mysite/suit/templates/suit/form_as_fieldset.html
<fieldset class="module aligned">
    {% for field in form %}
        <div class="control-group{{ field.errors|yesno:' error,' }}">
            <div class="control-label">
                {{ field.label_tag }}
            </div>
            <div class="controls">
                {{ field }}
                <div class="help-inline">{{ field.errors }}</div>
            </div>
        </div>
    {% endfor %}
</fieldset>

mysite/suit/templates/suit/includes/change_form_includes.html
{% for template, tab_position, tab in adminform.model_admin.suit_form_includes %}
  {% if position == tab_position or position == 'bottom' and not tab_position %}
    <div class="suit-include{% if tab %} suit-tab suit-tab-{{ tab }}{% endif %}">{% include template %}</div>
  {% endif %}
{% endfor %}

mysite/templates/polls/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="robots" content="noindex, nofollow">

    <title>Home</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
	<link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
	<link href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" rel="stylesheet" id="bootstrap-css">
 <style type="text/css">
    *{
    -webkit-box-sizing: border-box;
    box-sizing: border-box;
}

html, body{
	font-family: 'Century Gothic', sans-serif !important;
    height: 100%;
    margin: 0;
    padding: 0;
    background-color: #333;
    overflow: hidden;
	background: url(http://www.artnak.net/upload/2018/08/23/6f10caa9122ef563.png) no-repeat center center fixed;
    -webkit-background-size: cover;
    -moz-background-size: cover;
    -o-background-size: cover;
    background-size: cover;
}
canvas{
    background-color: transparent;
}

.card{
height: 345px;
margin-top: auto;
margin-bottom: auto;
width: 400px;
background-color: rgba(0,0,0,0.5) !important;
}
.card-header h3{
color: white;
}
.input-group-prepend span{
width: 40px;
background-color: #FFC312;
color: black;
border:0 !important;
}
input:focus{
outline: 0 0 0 0  !important;
box-shadow: 0 0 0 0 !important;

}
.remember{
color: white;
}

.remember input
{
width: 20px;
height: 20px;
margin-left: 15px;
margin-right: 5px;
}.login_btn{
color: black;
background-color: #FFC312;
width: 100px;
}

.login_btn:hover{
color: black;
background-color: white;
}

.links{
color: white;
}

.links a{
margin-left: 4px;
}
    </style>


</head>
<body>

<div class="container" >
	<div class="d-flex justify-content-center h-100" style="padding-top: 300px;">
		<div class="card" style="padding-top: 0px;">
			<div class="card-header">
				<h3 style="font-size: 40px;">SCMS</h3>
				<div class="d-flex justify-content-end social_icon">

				</div>
			</div>
			<div class="card-body">
				<form role="login" action="{% url 'polls:login' %}?next={{ next }}" method="post" id="form">
                            {% csrf_token %}
					<div class="input-group form-group">
						<div class="input-group-prepend">
							<span class="input-group-text"><i class="fa fa-user"></i></span>
						</div>
						<input name="username" type="text" class="form-control" placeholder="username">

					</div>
					<div class="input-group form-group">
						<div class="input-group-prepend">
							<span class="input-group-text"><i class="fa fa-key"></i></span>
						</div>
						<input name="password"  type="password" class="form-control" placeholder="password">
					</div>
					<div class="row align-items-center remember">
						<input type="checkbox">Remember Me
					</div>
					<div class="form-group">
						<input type="submit" value="Login" class="btn float-right login_btn">
					</div>
				</form>
			</div>
			<div class="card-footer">
				<div class="d-flex justify-content-center links">
					Contact to Administrator
				</div>

			</div>
		</div>
	</div>
	<canvas id="nokey" width="120%" height="120%" style="margin-top:-645px; margin-left: -36%; margin-right: -90%;"></canvas>
</div>


	<script type="text/javascript">
	var canvas = document.getElementById('nokey'),
   can_w = parseInt(canvas.getAttribute('width')),
   can_h = parseInt(canvas.getAttribute('height')),
   ctx = canvas.getContext('2d');

// console.log(typeof can_w);

var ball = {
      x: 0,
      y: 0,
      vx: 0,
      vy: 0,
      r: 0,
      alpha: 1,
      phase: 0
   },
   ball_color = {
       r: 207,
       g: 255,
       b: 4
   },
   R = 9,
   balls = [],
   alpha_f = 0.03,
   alpha_phase = 0,

// Line
   link_line_width = 2,
   dis_limit = 260,
   add_mouse_point = true,
   mouse_in = false,
   mouse_ball = {
      x: 0,
      y: 0,
      vx: 0,
      vy: 0,
      r: 0,
      type: 'mouse'
   };

// Random speed
function getRandomSpeed(pos){
    var  min = -1,
       max = 1;
    switch(pos){
        case 'top':
            return [randomNumFrom(min, max), randomNumFrom(0.1, max)];
            break;
        case 'right':
            return [randomNumFrom(min, -0.1), randomNumFrom(min, max)];
            break;
        case 'bottom':
            return [randomNumFrom(min, max), randomNumFrom(min, -0.1)];
            break;
        case 'left':
            return [randomNumFrom(0.1, max), randomNumFrom(min, max)];
            break;
        default:
            return;
            break;
    }
}
function randomArrayItem(arr){
    return arr[Math.floor(Math.random() * arr.length)];
}
function randomNumFrom(min, max){
    return Math.random()*(max - min) + min;
}
console.log(randomNumFrom(0, 10));
// Random Ball
function getRandomBall(){
    var pos = randomArrayItem(['top', 'right', 'bottom', 'left']);
    switch(pos){
        case 'top':
            return {
                x: randomSidePos(can_w),
                y: -R,
                vx: getRandomSpeed('top')[0],
                vy: getRandomSpeed('top')[1],
                r: R,
                alpha: 1,
                phase: randomNumFrom(0, 10)
            }
            break;
        case 'right':
            return {
                x: can_w + R,
                y: randomSidePos(can_h),
                vx: getRandomSpeed('right')[0],
                vy: getRandomSpeed('right')[1],
                r: R,
                alpha: 1,
                phase: randomNumFrom(0, 10)
            }
            break;
        case 'bottom':
            return {
                x: randomSidePos(can_w),
                y: can_h + R,
                vx: getRandomSpeed('bottom')[0],
                vy: getRandomSpeed('bottom')[1],
                r: R,
                alpha: 1,
                phase: randomNumFrom(0, 10)
            }
            break;
        case 'left':
            return {
                x: -R,
                y: randomSidePos(can_h),
                vx: getRandomSpeed('left')[0],
                vy: getRandomSpeed('left')[1],
                r: R,
                alpha: 1,
                phase: randomNumFrom(0, 10)
            }
            break;
    }
}
function randomSidePos(length){
    return Math.ceil(Math.random() * length);
}

// Draw Ball
function renderBalls(){
    Array.prototype.forEach.call(balls, function(b){
       if(!b.hasOwnProperty('type')){
           ctx.fillStyle = 'rgba('+ball_color.r+','+ball_color.g+','+ball_color.b+','+b.alpha+')';
           ctx.beginPath();
           ctx.arc(b.x, b.y, R, 0, Math.PI*2, true);
           ctx.closePath();
           ctx.fill();
       }
    });
}

// Update balls
function updateBalls(){
    var new_balls = [];
    Array.prototype.forEach.call(balls, function(b){
        b.x += b.vx;
        b.y += b.vy;

        if(b.x > -(50) && b.x < (can_w+50) && b.y > -(50) && b.y < (can_h+50)){
           new_balls.push(b);
        }

        // alpha change
        b.phase += alpha_f;
        b.alpha = Math.abs(Math.cos(b.phase));
        // console.log(b.alpha);
    });

    balls = new_balls.slice(0);
}

// loop alpha
function loopAlphaInf(){

}

// Draw lines
function renderLines(){
    var fraction, alpha;
    for (var i = 0; i < balls.length; i++) {
        for (var j = i + 1; j < balls.length; j++) {

           fraction = getDisOf(balls[i], balls[j]) / dis_limit;

           if(fraction < 1){
               alpha = (1 - fraction).toString();

               ctx.strokeStyle = 'rgba(150,150,150,'+alpha+')';
               ctx.lineWidth = link_line_width;

               ctx.beginPath();
               ctx.moveTo(balls[i].x, balls[i].y);
               ctx.lineTo(balls[j].x, balls[j].y);
               ctx.stroke();
               ctx.closePath();
           }
        }
    }
}

// calculate distance between two points
function getDisOf(b1, b2){
    var  delta_x = Math.abs(b1.x - b2.x),
       delta_y = Math.abs(b1.y - b2.y);

    return Math.sqrt(delta_x*delta_x + delta_y*delta_y);
}

// add balls if there a little balls
function addBallIfy(){
    if(balls.length < 30){
        balls.push(getRandomBall());
    }
}

// Render
function render(){
    ctx.clearRect(0, 0, can_w, can_h);

    renderBalls();

    renderLines();

    updateBalls();

    addBallIfy();

    window.requestAnimationFrame(render);
}

// Init Balls
function initBalls(num){
    for(var i = 1; i <= num; i++){
        balls.push({
            x: randomSidePos(can_w),
            y: randomSidePos(can_h),
            vx: getRandomSpeed('top')[0],
            vy: getRandomSpeed('top')[1],
            r: R,
            alpha: 1,
            phase: randomNumFrom(0, 10)
        });
    }
}
// Init Canvas
function initCanvas(){
    canvas.setAttribute('width', window.innerWidth);
    canvas.setAttribute('height', window.innerHeight);

    can_w = parseInt(canvas.getAttribute('width'));
    can_h = parseInt(canvas.getAttribute('height'));
}
window.addEventListener('resize', function(e){
    console.log('Window Resize...');
    initCanvas();
});

function goMovie(){
    initCanvas();
    initBalls(20);
    window.requestAnimationFrame(render);
}
goMovie();

// Mouse effect
canvas.addEventListener('mouseenter', function(){
    console.log('mouseenter');
    mouse_in = true;
    balls.push(mouse_ball);
});
canvas.addEventListener('mouseleave', function(){
    console.log('mouseleave');
    mouse_in = false;
    var new_balls = [];
    Array.prototype.forEach.call(balls, function(b){
        if(!b.hasOwnProperty('type')){
            new_balls.push(b);
        }
    });
    balls = new_balls.slice(0);
});
canvas.addEventListener('mousemove', function(e){
    var e = e || window.event;
    mouse_ball.x = e.pageX;
    mouse_ball.y = e.pageY;
    // console.log(mouse_ball);
});

	</script>
</body>
</html>

mysite/templates/polls/login2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="robots" content="noindex, nofollow">

    <title>Password Strength Meter - Bootsnipp.com</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <style type="text/css">
    @CHARSET "UTF-8";
/*
over-ride "Weak" message, show font in dark grey
*/

.progress-bar {
    color: #333;
} 

/*
Reference:
http://www.bootstrapzen.com/item/135/simple-login-form-logo/
*/

* {
    -webkit-box-sizing: border-box;
	   -moz-box-sizing: border-box;
	        box-sizing: border-box;
	outline: none;
}

    .form-control {
	  position: relative;
	  font-size: 16px;
	  height: auto;
	  padding: 10px;
		@include box-sizing(border-box);

		&:focus {
		  z-index: 2;
		}
	}

body {
	background: url(http://i.imgur.com/GHr12sH.jpg) no-repeat center center fixed;
    -webkit-background-size: cover;
    -moz-background-size: cover;
    -o-background-size: cover;
    background-size: cover;
}

.login-form {
	margin-top: 60px;
}

form[role=login] {
	color: #5d5d5d;
	background: #f2f2f2;
	padding: 26px;
	border-radius: 10px;
	-moz-border-radius: 10px;
	-webkit-border-radius: 10px;
}
	form[role=login] img {
		display: block;
		margin: 0 auto;
		margin-bottom: 35px;
	}
	form[role=login] input,
	form[role=login] button {
		font-size: 18px;
		margin: 16px 0;
	}
	form[role=login] > div {
		text-align: center;
	}
	
.form-links {
	text-align: center;
	margin-top: 1em;
	margin-bottom: 50px;
}
	.form-links a {
		color: #fff;
	}    </style>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>

</head>
<body>
    <div class="container">
  
  <div class="row" id="pwd-container">
    <div class="col-md-4"></div>
    
    <div class="col-md-4">
      <section class="login-form" style="padding-top: 200px;">
{#        <form method="post" action="#" role="login">#}
            <form role="login" action="{% url 'polls:login' %}?next={{ next }}" method="post" id="form">
                            {% csrf_token %}
          <img src="http://i.imgur.com/RcmcLv4.png" class="img-responsive" alt="" />
          <input type="text" name="username" placeholder="account" required class="form-control input-lg" />
          
          <input name="password" type="password" class="form-control input-lg" id="password" placeholder="Password" required="" />
          
          
          <div class="pwstrength_viewport_progress"></div>
          
          
          <button type="submit" name="go" class="btn btn-lg btn-primary btn-block">Sign in</button>
          <div>
{#            <a href="#">Create account</a> or <a href="#">reset password</a>#}
          </div>
          
        </form>
        
{#        <div class="form-links">#}
{#          <a href="#">www.website.com</a>#}
{#        </div>#}
      </section>  
      </div>
      
      <div class="col-md-4"></div>
      

  </div>
  
  <p>
    
  </p>     
  

</body>
</html>

mysite/templates/sb-admin/navbar.html
<nav class="navbar navbar-default navbar-fixed-top" role="navigation" style="margin-bottom: 120px;">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">CorePyTool</a>
            </div>
            <!-- /.navbar-header -->


            <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">
                        <!---
                        <li class="sidebar-search">
                            <div class="input-group custom-search-form">
                                <input type="text" class="form-control" placeholder="Search...">
                                <span class="input-group-btn">
                                <button class="btn btn-default" type="button">
                                    <i class="fa fa-search"></i>
                                </button>
                            </span>
                            </div>
                            <!-- /input-group -->
                        <!-- </li>
                        -->
                        <li>
                            <a href="/admin"><i class="fa fa-database fa-fw"></i> Database</a>
                        </li>
                        <li>
                            <a href="{% url 'polls:file_upload'  %}"><i class="fa fa-database fa-fw"></i> File Upload</a>
                        </li>
                        <li>
                            <a href="{% url 'polls:load_page' 'index' %}"><i class="fa fa-dashboard fa-fw"></i> Dashboard</a>
                        </li>
                        {% if devmode %}
                        <li>
                            <a href="#"><i class="fa fa-bar-chart-o fa-fw"></i> Charts<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a href="{% url 'polls:load_page' 'highcharts' %}">Highchart Charts</a>
                                </li>
{#                                <li>#}
{#                                    <a href="{% url 'polls:load_page' 'morris' %}">Morris.js Charts</a>#}
{#                                </li>#}
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>
                        <li>
                            <a href="{% url 'polls:load_page' 'tables' %}"><i class="fa fa-table fa-fw"></i> Tables</a>
                        </li>
                        <li>
                            <a href="{% url 'polls:load_page' 'forms' %}"><i class="fa fa-edit fa-fw"></i> Forms</a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-wrench fa-fw"></i> UI Elements<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a href="{% url 'polls:load_page' 'panels-wells' %}">Panels and Wells</a>
                                </li>
                                <li>
                                    <a href="{% url 'polls:load_page' 'buttons' %}">Buttons</a>
                                </li>
                                <li>
                                    <a href="{% url 'polls:load_page' 'notifications' %}">Notifications</a>
                                </li>
                                <li>
                                    <a href="{% url 'polls:load_page' 'typography' %}">Typography</a>
                                </li>
                                <li>
                                    <a href="{% url 'polls:load_page' 'icons' %}"> Icons</a>
                                </li>
                                <li>
                                    <a href="{% url 'polls:load_page' 'grid' %}">Grid</a>
                                </li>
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-sitemap fa-fw"></i> Multi-Level Dropdown<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a href="#">Second Level Item</a>
                                </li>
                                <li>
                                    <a href="#">Second Level Item</a>
                                </li>
                                <li>
                                    <a href="#">Third Level <span class="fa arrow"></span></a>
                                    <ul class="nav nav-third-level">
                                        <li>
                                            <a href="#">Third Level Item</a>
                                        </li>
                                        <li>
                                            <a href="#">Third Level Item</a>
                                        </li>
                                        <li>
                                            <a href="#">Third Level Item</a>
                                        </li>
                                        <li>
                                            <a href="#">Third Level Item</a>
                                        </li>
                                    </ul>
                                    <!-- /.nav-third-level -->
                                </li>
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-files-o fa-fw"></i> Sample Pages<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a href="{% url 'polls:load_page' 'blank' %}">Blank Page</a>
                                </li>
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>
                        {%  endif %}
                        <li>
                            <a href="{% url 'polls:load_page' 'about' %}"><i class="fa fa-info-circle fa-fw"></i> About</a>
                        </li>
                    </ul>
                </div>
                <!-- /.sidebar-collapse -->
            </div>
            <!-- /.navbar-static-side -->
        </nav>